######################################################################
##
## Filename: FA_tb.udo
## Created on: Thu Jul 16 5:02:22 Hora estándar romance 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
